<?php
global $zon;
$slug = str_replace("-", " ", urldecode($zon['page'][1]));
$page = getPageBySlug($slug);
?>
<div class="mx-2">
    <div class="flex gap-4 page-content-container">
        <?php echo LoadFile('navbar/content') ?>
        <div class="page-content bg-white p-6 w-full">
            <h1 class="mb-4"><?= $page['title'] ?></h1>
            <?= $page['content'] ?>
        </div>
    </div>
</div>