<?php global $site_url; ?>
<div class="flex items-center justify-center px-4 h-[80vh]">
    <form id="login-form" method="post" class="login-form bg-white p-8 rounded-xl w-[400px] ">
        <div class="input-group mb-4">
            <label for="" class="mb-2 transition duration-300  block font-medium">Email & Username</label>
            <input required name="usernameEmail" placeholder="zontal@mvnthemes.com" type="text"
                class="hover:border-[var(--theme-color)] focus:outline-[var(--theme-color)] px-4 w-full py-4 bg-transparent border rounded-lg border-gray-400 " />
        </div>
        <div class="input-group">
            <label for="" class="mb-2 transition duration-300  block font-medium">Password</label>
            <input required name="password" placeholder="#######" type="password"
                class="px-4 w-full py-4 hover:border-[var(--theme-color)] focus:outline-[var(--theme-color)]  bg-transparent rounded-lg border border-gray-400 " />
        </div>
        <button type="submit" class="w-full disabled:opacity-70 mt-3 py-3 text-white bg-[var(--theme-color)] rounded-full px-4">Login</button>
    </form>
</div>